name: 'db_portfolio'
version: '1.0.0'
profile: 'db_portfolio'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  db_portfolio:
    staging:
      +materialized: view
      apc_wellness:
        +schema: stg_apc_wellness
    intermediate:
      +materialized: view
      apc_wellness:
        +schema: int_apc_wellness
    marts:
      +materialized: table
      apc_wellness:
        +schema: mart_apc_wellness